import './globals.css';
import { Roboto } from 'next/font/google';
import { Header } from 'components/Header/Header';
import { Footer } from 'components/Footer/Footer';

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        <div className="mainContainer">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
